### ISSUE TITLE
[Bug]: 下载主题失败, 提示 Error: Request failed, status 403

### ISSUE THREAD

**Issue by probe301** [PKM-er/Pkmer-Obsidian#19]
### Bug Description

首先感谢 PKMer 提供这项服务!

问题重现步骤: 

登录 PKMer Market, 用它下载一个插件, 正常, 
之后切到 "下载主题界面", 在确认自己还有剩余使用次数时, 选一个主题, 点击下载, 报错 

```js
welcome Pkmer Market
Error: Request failed, status 403
    at new t (app.js:1:1782334)
    at Bq (app.js:1:1782526)
    at app.js:1:1783203
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at a (app.js:1:236367)
```

截图1
![image](https://github.com/PKM-er/Pkmer-Obsidian/assets/1049804/fc0ba8fb-0e80-4392-90d4-f31bc2f5435f)

更完整截图2
![image](https://github.com/PKM-er/Pkmer-Obsidian/assets/1049804/653313e2-84dc-4dc6-8178-4e947ba4b4f2)

过程中, 唯一见到的 Notice 来自 `lt.Notice(`主题 ${e}安装失败！${i}`,5e3),` 其余几个 Notice 未弹出

---

个人猜测: 也许与这个 `requestUrl(url)` 时, 里面含 emoji 或空格有关

---

最后, 仅剩一次下载次数了, 我把机会给了命名里 "不带空格, 不带 emoji" 的主题, 下载成功!

### Obsidian Version

1.5.8

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by probe301** [comment]
此外是否可以设置为, 如果在 PKMer 市场下载失败了, 不扣他使用次数?
(这优惠仅给 "下载次数 < 10 的新手用户", 老手就不管他了)


现在状况是, 我没下载到主题, 但是次数没了, 感觉推广起来有点困难啊

**Comment by windily-cloud** [comment]
> 此外是否可以设置为, 如果在 PKMer 市场下载失败了, 不扣他使用次数? (这优惠仅给 "下载次数 < 10 的新手用户", 老手就不管他了)
> 
> 现在状况是, 我没下载到主题, 但是次数没了, 感觉推广起来有点困难啊

问题是不知道下载失败没。    判断是否下载是根据是否用了服务器资源，如果确实传了插件数据，那么就判断为下载了。有些插件它下载下来本身安装不了，或者其他意外情况，这只能给出插件名挨个儿打补丁。

如果依据是是否成功安装，那用户只下载不安装，就可以无限制占用服务器资源，这也不可取。

目前这方面有在优化逻辑，有问题建议把插件名也带上。

**Comment by probe301** [comment]
> 判断是否下载是根据是否用了服务器资源，如果确实传了插件数据，那么就判断为下载了。有些插件它下载下来本身安装不了，或者其他意外情况，这只能给出插件名挨个儿打补丁。

理解这其中的困难, 维护一个服务不容易!

做为用户, 我自己只要前几次尝试下载时没遇到巨大挫折, 就会用下去
目前在这个市场里, 大部分插件和主题都是能顺利下载的


> 目前这方面有在优化逻辑，有问题建议把插件名也带上。

好的, 如果发现了我会上报
